name: 'Test'
on: [push]
jobs:
  run-action:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Dependencys
        run: npm ci
      - name: Build
        run: npm run build
      - name: Mutation Test
        uses: ./
